Rules = [
    "Elemental Selection: Choose elements that form a single-phase solid solution or a simple eutectic system. The elements Al, Co, Cr, Fe, Ni are commonly used in EHEAs due to their compatibility and ability to form stable high-entropy mixtures.",
    "Optional Elements Effect: Cu enhances corrosion resistance and conductivity but may lower thermal stability. Mn alters fluidity and solidification, risking casting defects and phase instability, leading to unwanted phases or microstructures.",
    "Atomic Size Difference: The atomic radii of the constituent elements should differ by a margin of 5% to 15%, a range that assists in maintaining a stable solid solution while simultaneously minimizing lattice distortion. ~\\ref{Microstructure evolution and mechanical properties of a novel CrNbTiZrAlx (0.25 ≤ x ≤ 1.25) eutectic refractory high-entropy alloy} and \\ref{Hume-Rothery}",
    "Valence Electron Concentration (VEC): The VEC should be in a range that favors the formation of desired phases (like FCC, BCC, or HCP). The phase stability in high entropy alloys is often influenced by the electron concentration.",
    "Mixing Enthalpy: Select elements with negative or low positive mixing enthalpies to promote solid solution formation and reduce the tendency for intermetallic compound formation. ~\\ref{Seaweed eutectic-dendritic solidification pattern in a CoCrFeNiMnPd eutectic high-entropy alloy}",
    "Advancing Green Manufacturing: To maintain the intrinsic strength and castability of eutectic high entropy alloys with minimal heat treatment and post-processing, adherence to green manufacturing principles is essential, streamlining the production process.",
    "Phase Diagram Analysis: Identify eutectic points where a simple solid solution or a combination of phases (like FCC+B2) can form. Look for compositions that avoid brittle intermetallic phases. Select compositions near eutectic points that favor the formation of desired solid solution phases.",
    "Weighted Average Physical Properties: Consider the weighted average of physical properties like melting point, density, and elasticity of the constituent elements."
]